"""
This script analyzes chunk-averaged data generated by LAMMPS
"""

import numpy as np
import matplotlib.pyplot as plt

##Next two lines are for testing 
##PATH="/home/sr802/Dropbox/PhD/Cambridge/Academical/3.Simulation/0.Lammps/2.Solid_fluid/2D"
##TotalPath=PATH+"/parameters.dat"

#Reading the 

#Reading the times to make it easier to read the file by chunks
Times=np.loadtxt("Times.dat",dtype=int)
x=np.size(Times)

#Getting the shape of the array 
File_Name=str(int(Times[0]))+".chunk"
n,m=np.shape(np.loadtxt(File_Name,skiprows=1)) 

Averages=np.zeros((n,2))


for k in xrange(x): #Runs over the sampled times.
    print("Reading configuration %d of %d" %(k,x-1))
    File_Name=str(int(Times[k]))+".chunk"
    Chunk_Results=np.loadtxt(File_Name,skiprows=1) #Bonded Particles from oxDNA
    
    Averages[:,1]=Averages[:,1]+Chunk_Results[:,5]*Chunk_Results[:,6]  #To set the Pyy 
    
Averages[:,0]=Chunk_Results[:,1]
Averages[:,1]=-Averages[:,1]/(k+1) #*25.6871345049201*0.642178362623003*0.5


plt.plot(Averages[:,0],Averages[:,1])

"""Creating the output file"""
np.savetxt("Averages.dat",Averages,header="Height,Pyy")







#
#FILE_NAME="cut"
#
###Display the header file
##f=open(FILE_NAME, 'r')
##FirstLine=f.readline().split()
##f.close()
#
#Param=np.loadtxt(FILE_NAME,skiprows=1)
#n,m=np.shape(Param)
#Nsampling=int(n*0.5) #This is the number of interations, it took the system to stabilize (It is guessed)
##plt.plot(Param[:,6])
#
##plt.figure(2)
##plt.plot(Param[:,5])
#
##plt.figure(2)
##plt.plot(Param[:,1])
#
##for i in xrange(m):
##    print "The Average %s is %lf " %(FirstLine[i],np.average(Param[Nsampling::,i]))
##
##plt.plot(Param[:,0],Param[:,2])
