#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 14 18:24:28 2018
Test of LJ melting
@author: simon
"""

from lammps import IPyLammps
# 3d Lennard-Jones melt

L = IPyLammps() #Creates the object
L.units("lj")
L.atom_style("atomic")
L.atom_modify("map array")

L.lattice("fcc", 0.8442)
L.region("box block", 0, 4, 0, 4, 0, 4)
L.create_box(1, "box")
L.create_atoms(1, "box")
L.mass(1, 1.0)

L.velocity("all create", 1.44, 87287, "loop geom")

L.pair_style("lj/cut", 2.5)
L.pair_coeff(1, 1, 1.0, 1.0, 2.5)

L.neighbor(0.3, "bin")
L.neigh_modify("delay 0 every 20 check no")

L.fix("1 all nve")

L.variable("fx atom fx")
L.write_script
L.run(100)

L.dump("id", "all", "atom", "50", "dump.melt")
L.command("compute gr all rdf 100 1 1 cutoff 2.0")
L.fix(" 2 all ave/time 1 1 1 c_gr[*] file gr.dat mode vector")
L.dump(" da2 all custom 1 config.dat id type x y z ix iy iz vx vy vz")


#dump da2 all custom ${myDump} ./conf/dumpfile*.gz id type x y z ix iy iz vx vy vz

#L.command("compute", "1",  "all", "rdf", "100", "1", "1")

L.run(1)

